"""Create Chef1 model

Revision ID: 19796d901d17
Revises: 468a48cdf1f9
Create Date: 2024-01-20 10:25:06.115528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19796d901d17'
down_revision = '468a48cdf1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chef',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chef_name', sa.String(length=100), nullable=False),
    sa.Column('chef_image', sa.String(length=400), nullable=True),
    sa.Column('chef_speciality', sa.String(length=100), nullable=True),
    sa.Column('chef_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chef')
    # ### end Alembic commands ###
