"""Create Chef2 model

Revision ID: fe2a315530cf
Revises: 19796d901d17
Create Date: 2024-01-20 10:30:35.446819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2a315530cf'
down_revision = '19796d901d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chef_city', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.drop_column('chef_city')

    # ### end Alembic commands ###
